import type { AnalysisResult } from "@/types";

export const MOCK_ANALYSIS_RESULT: AnalysisResult = {
  document: {
    document_id: "mock-001",
    pages: 14,
    total_clauses: 18,
    processing_time_ms: 2340,
  },
  summary: {
    overall_risk_score: 54.2,
    risk_level: "medium",
    high_risk_count: 4,
    medium_risk_count: 8,
    low_risk_count: 6,
  },
  entities: {
    parties: ["Acme Corporation", "John Smith", "TechVentures Inc."],
    dates: ["January 15, 2025", "December 31, 2026"],
    amounts: ["$500,000", "$2,500 per month"],
    jurisdictions: ["State of Delaware", "New York"],
  },
  clauses: [
    {
      id: 0,
      text: "The Company shall indemnify, defend, and hold harmless the Executive and his heirs, executors, and administrators from and against any and all liability, claims, damages, losses, costs and expenses, including reasonable attorney fees, arising out of or relating to any acts or omissions of the Executive in connection with the performance of his duties hereunder.",
      type: "Indemnification",
      confidence: 0.932,
      risk_score: 82.4,
      risk_level: "high",
      is_unfair: true,
      entities: {
        parties: ["the Company", "the Executive"],
        dates: [],
        amounts: [],
      },
      explanation:
        "This indemnification clause is extremely broad and one-sided, requiring the Company to cover all legal costs and liabilities for the Executive's actions. The phrase 'any and all liability' with no carve-outs for gross negligence or intentional misconduct is a significant red flag — it could obligate the Company to defend conduct that is clearly wrongful. Negotiate to exclude gross negligence, fraud, and willful misconduct from the indemnification scope.",
      top_risk_terms: [
        "indemnify",
        "hold harmless",
        "any and all liability",
        "acts or omissions",
        "reasonable attorney fees",
      ],
    },
    {
      id: 1,
      text: "In no event shall either party be liable for any indirect, incidental, special, exemplary, or consequential damages, including but not limited to, loss of revenue, loss of profits, loss of business, or loss of data, whether in an action of contract or tort, arising out of or in connection with this Agreement.",
      type: "Limitation of Liability",
      confidence: 0.911,
      risk_score: 76.1,
      risk_level: "high",
      is_unfair: true,
      entities: { parties: ["either party"], dates: [], amounts: [] },
      explanation:
        "This limitation of liability clause completely excludes consequential damages, which can be devastating if a data breach or service failure results in lost revenue. The phrase 'including but not limited to loss of data' is particularly concerning for technology contracts, as data loss can be catastrophic. Ensure there are carve-outs for indemnification obligations and confidentiality breaches.",
      top_risk_terms: [
        "limitation",
        "liability",
        "consequential damages",
        "indirect",
        "loss of data",
      ],
    },
    {
      id: 2,
      text: "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without giving effect to any choice or conflict of law provision or rule. Any legal suit, action, or proceeding arising out of or related to this Agreement shall be instituted exclusively in the federal courts of Delaware.",
      type: "Governing Law",
      confidence: 0.887,
      risk_score: 38.5,
      risk_level: "medium",
      is_unfair: false,
      entities: { parties: [], dates: [], amounts: [] },
      explanation:
        "The governing law clause designates Delaware as the exclusive jurisdiction, which is standard but can be inconvenient if your business operates in another state. The exclusivity of Delaware federal courts means you would need to litigate there even for small disputes, potentially increasing legal costs. Consider negotiating for arbitration or your home state jurisdiction if Delaware is impractical.",
      top_risk_terms: [
        "exclusively",
        "governed by",
        "Delaware",
        "construed",
        "without giving effect",
      ],
    },
    {
      id: 3,
      text: "Either party may terminate this Agreement at any time, with or without cause, by providing thirty (30) days written notice to the other party. Upon termination, all outstanding payments shall become immediately due and payable.",
      type: "Termination",
      confidence: 0.956,
      risk_score: 61.3,
      risk_level: "medium",
      is_unfair: false,
      entities: { parties: ["Either party"], dates: [], amounts: [] },
      explanation:
        "The termination at will provision with only 30 days notice creates business continuity risk, particularly if this is a critical service agreement. The clause accelerating all outstanding payments upon termination is aggressive and could create cash flow problems. Consider negotiating for a longer notice period (60-90 days) and a payment cure period before acceleration.",
      top_risk_terms: [
        "terminate",
        "at any time",
        "immediately due",
        "outstanding payments",
        "without cause",
      ],
    },
    {
      id: 4,
      text: "The Executive agrees that during the term of employment and for a period of two (2) years following termination, Executive shall not directly or indirectly engage in any business that competes with the Company within the United States.",
      type: "Non-Compete",
      confidence: 0.943,
      risk_score: 88.7,
      risk_level: "high",
      is_unfair: true,
      entities: {
        parties: ["the Executive", "the Company"],
        dates: [],
        amounts: [],
      },
      explanation:
        "This non-compete clause is extremely broad and arguably unenforceable in many jurisdictions — covering the entire United States for 2 years is a very wide scope. The vague definition of 'competes with the Company' could prevent completely unrelated work. In states like California this would be void; even in Delaware it faces scrutiny. Negotiate to narrow the geographic scope to specific markets and clarify what constitutes competition.",
      top_risk_terms: [
        "non-compete",
        "United States",
        "two years",
        "directly or indirectly",
        "any business",
      ],
    },
    {
      id: 5,
      text: "All intellectual property, inventions, improvements, discoveries, and works of authorship, whether or not patentable, which are made or conceived by Employee during the term of employment, whether or not during working hours, shall be the exclusive property of the Company.",
      type: "Intellectual Property",
      confidence: 0.899,
      risk_score: 79.2,
      risk_level: "high",
      is_unfair: true,
      entities: {
        parties: ["Employee", "the Company"],
        dates: [],
        amounts: [],
      },
      explanation:
        "The IP assignment clause captures all creations 'whether or not during working hours,' which means personal projects and side work could be claimed by the Company. This is overly broad — without a carve-out for inventions unrelated to the Company's business, the Company could claim ownership of your personal creative work. Many states require employers to exclude IP created entirely on personal time with personal resources.",
      top_risk_terms: [
        "intellectual property",
        "whether or not",
        "working hours",
        "exclusive property",
        "all inventions",
      ],
    },
    {
      id: 6,
      text: "Employee shall keep confidential all proprietary information, trade secrets, and business information of the Company and shall not disclose such information to any third party without prior written consent.",
      type: "Confidentiality",
      confidence: 0.921,
      risk_score: 29.8,
      risk_level: "low",
      is_unfair: false,
      entities: {
        parties: ["Employee", "the Company"],
        dates: [],
        amounts: [],
      },
      explanation:
        "This confidentiality clause appears standard with low risk.",
      top_risk_terms: [],
    },
    {
      id: 7,
      text: "The Company shall pay Employee a base salary of $120,000 per year, payable in accordance with the Company's normal payroll practices, subject to applicable withholding and deductions.",
      type: "Compensation",
      confidence: 0.978,
      risk_score: 12.5,
      risk_level: "low",
      is_unfair: false,
      entities: {
        parties: ["the Company", "Employee"],
        dates: [],
        amounts: ["$120,000"],
      },
      explanation: "This compensation clause appears standard with low risk.",
      top_risk_terms: [],
    },
  ],
};
